/* ---------- DROP TABLES (каскадне видалення обмежень) ---------- */
DROP TABLE AUTHORIZATIONS CASCADE CONSTRAINTS;
DROP TABLE IDENTIFICATION CASCADE CONSTRAINTS;
DROP TABLE NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE RECOMMENDATION CASCADE CONSTRAINTS;
DROP TABLE THREAT CASCADE CONSTRAINTS;
DROP TABLE DELIVERY CASCADE CONSTRAINTS;
DROP TABLE ORDER_T CASCADE CONSTRAINTS;
DROP TABLE RESTAURANT CASCADE CONSTRAINTS;
DROP TABLE USER_T CASCADE CONSTRAINTS;
DROP TABLE SYSTEM_T CASCADE CONSTRAINTS;

/* ======================= CREATE TABLES ======================== */

/* Користувач */
CREATE TABLE USER_T (
    USER_ID NUMBER(10),
    USER_NAME VARCHAR2(100),
    PREFERENCES VARCHAR2(200),
    NOTIFICATION_SETTINGS VARCHAR2(100)
);

ALTER TABLE USER_T ADD CONSTRAINT PK_USER PRIMARY KEY (USER_ID);
ALTER TABLE USER_T MODIFY (USER_NAME NOT NULL);

/* Система */
CREATE TABLE SYSTEM_T (
    SYSTEM_ID NUMBER(10),
    SYSTEM_VERSION VARCHAR2(20)
);

ALTER TABLE SYSTEM_T ADD CONSTRAINT PK_SYSTEM PRIMARY KEY (SYSTEM_ID);
ALTER TABLE SYSTEM_T MODIFY (SYSTEM_VERSION NOT NULL);
ALTER TABLE SYSTEM_T ADD CONSTRAINT CHK_SYSTEM_VERSION
CHECK (REGEXP_LIKE(SYSTEM_VERSION, '^[0-9]+(\.[0-9]+){1,2}$'));
/* формат: 1.0 або 1.2.3 */

/* Ресторан (БЕЗ ORDER_ID) */
CREATE TABLE RESTAURANT (
    RESTAURANT_ID NUMBER(10),
    RESTAURANT_NAME VARCHAR2(150),
    RESTAURANT_ADDRESS VARCHAR2(200)
);

ALTER TABLE RESTAURANT ADD CONSTRAINT PK_RESTAURANT
PRIMARY KEY (RESTAURANT_ID);
ALTER TABLE RESTAURANT MODIFY (RESTAURANT_NAME NOT NULL);

/* Замовлення (Order) — уникаємо ключового слова ORDER */
CREATE TABLE ORDER_T (
    ORDER_ID NUMBER(12),
    DISHES VARCHAR2(500),
    ORDER_STATUS VARCHAR2(20),
    DELIVERY_TIME DATE,
    USER_ID NUMBER(10),
    RESTAURANT_ID NUMBER(10)
);

ALTER TABLE ORDER_T ADD CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_ID);
ALTER TABLE ORDER_T MODIFY (USER_ID NOT NULL);
ALTER TABLE ORDER_T MODIFY (RESTAURANT_ID NOT NULL);
ALTER TABLE ORDER_T ADD CONSTRAINT FK_ORDER_USER
FOREIGN KEY (USER_ID) REFERENCES USER_T (USER_ID);
ALTER TABLE ORDER_T ADD CONSTRAINT FK_ORDER_RESTAURANT
FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (RESTAURANT_ID);
ALTER TABLE ORDER_T ADD CONSTRAINT CHK_ORDER_STATUS
CHECK (ORDER_STATUS IN ('new', 'processing', 'delivered', 'cancelled'));

/* Доставка (1:1 з ORDER_T) */
CREATE TABLE DELIVERY (
    DELIVERY_ID NUMBER(12),
    DELIVERY_ADDRESS VARCHAR2(200),
    DELIVERY_AT DATE,
    ORDER_ID NUMBER(12)
);

ALTER TABLE DELIVERY ADD CONSTRAINT PK_DELIVERY
PRIMARY KEY (DELIVERY_ID);
ALTER TABLE DELIVERY MODIFY (ORDER_ID NOT NULL);
ALTER TABLE DELIVERY ADD CONSTRAINT UQ_DELIVERY_ORDER UNIQUE (ORDER_ID);
ALTER TABLE DELIVERY ADD CONSTRAINT FK_DELIVERY_ORDER
FOREIGN KEY (ORDER_ID) REFERENCES ORDER_T (ORDER_ID);

/* ---------- RECOMMENDATION ---------- */
CREATE TABLE RECOMMENDATION (
    RECOMMENDATION_ID NUMBER(12),
    REC_TEXT VARCHAR2(300),
    CRITERIA VARCHAR2(200),
    SYSTEM_ID NUMBER(10),
    USER_ID NUMBER(10)
);

ALTER TABLE RECOMMENDATION ADD CONSTRAINT PK_RECOMMENDATION
PRIMARY KEY (RECOMMENDATION_ID);
ALTER TABLE RECOMMENDATION MODIFY (SYSTEM_ID NOT NULL);
ALTER TABLE RECOMMENDATION MODIFY (USER_ID NOT NULL);
ALTER TABLE RECOMMENDATION ADD CONSTRAINT FK_REC_SYSTEM
FOREIGN KEY (SYSTEM_ID) REFERENCES SYSTEM_T (SYSTEM_ID);
ALTER TABLE RECOMMENDATION ADD CONSTRAINT FK_REC_USER
FOREIGN KEY (USER_ID) REFERENCES USER_T (USER_ID);

/* ---------- NOTIFICATION ---------- */
CREATE TABLE NOTIFICATION (
    NOTIFICATION_ID NUMBER(12),
    MESSAGE_TEXT VARCHAR2(300),
    SENT_AT DATE,
    SYSTEM_ID NUMBER(10),
    USER_ID NUMBER(10)
);

ALTER TABLE NOTIFICATION ADD CONSTRAINT PK_NOTIFICATION
PRIMARY KEY (NOTIFICATION_ID);
ALTER TABLE NOTIFICATION MODIFY (SYSTEM_ID NOT NULL);
ALTER TABLE NOTIFICATION MODIFY (USER_ID NOT NULL);
ALTER TABLE NOTIFICATION ADD CONSTRAINT FK_NOTIF_SYSTEM
FOREIGN KEY (SYSTEM_ID) REFERENCES SYSTEM_T (SYSTEM_ID);
ALTER TABLE NOTIFICATION ADD CONSTRAINT FK_NOTIF_USER
FOREIGN KEY (USER_ID) REFERENCES USER_T (USER_ID);

/* ---------- THREAT ---------- */
CREATE TABLE THREAT (
    THREAT_ID NUMBER(12),
    THREAT_DESCRIPTION VARCHAR2(300),
    RISK_SEVERITY VARCHAR2(10),
    SYSTEM_ID NUMBER(10)
);

ALTER TABLE THREAT ADD CONSTRAINT PK_THREAT
PRIMARY KEY (THREAT_ID);

ALTER TABLE THREAT MODIFY (SYSTEM_ID NOT NULL);

ALTER TABLE THREAT ADD CONSTRAINT FK_THREAT_SYSTEM
FOREIGN KEY (SYSTEM_ID) REFERENCES SYSTEM_T (SYSTEM_ID);

ALTER TABLE THREAT ADD CONSTRAINT CHK_THREAT_RISK
CHECK (RISK_SEVERITY IN ('low', 'medium', 'high'));

/* ---------- IDENTIFICATION (1:1 WITH USER_T) ---------- */
CREATE TABLE IDENTIFICATION (
    IDENTIFICATION_ID NUMBER(12),
    IDENTIFIER VARCHAR2(64),
    USER_ID NUMBER(10)
);

ALTER TABLE IDENTIFICATION ADD CONSTRAINT PK_IDENTIFICATION
PRIMARY KEY (IDENTIFICATION_ID);
ALTER TABLE IDENTIFICATION MODIFY (IDENTIFIER NOT NULL);
ALTER TABLE IDENTIFICATION ADD CONSTRAINT UQ_IDENT_USER UNIQUE (USER_ID);
ALTER TABLE IDENTIFICATION ADD CONSTRAINT FK_IDENT_USER
FOREIGN KEY (USER_ID) REFERENCES USER_T (USER_ID);
ALTER TABLE IDENTIFICATION ADD CONSTRAINT CHK_IDENTIFIER_FORMAT
CHECK (REGEXP_LIKE(IDENTIFIER, '^[A-Za-z0-9_-]{3,64}$'));

/* ---------- AUTHORIZATIONS (1:1 WITH IDENTIFICATION) ---------- */
CREATE TABLE AUTHORIZATIONS (
    AUTHORIZATION_ID NUMBER(12),
    ACCESS_LEVEL VARCHAR2(20),
    IDENTIFICATION_ID NUMBER(12)
);

ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT PK_AUTHORIZATION
PRIMARY KEY (AUTHORIZATION_ID);
ALTER TABLE AUTHORIZATIONS MODIFY (IDENTIFICATION_ID NOT NULL);
ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT UQ_AUTH_IDENT
UNIQUE (IDENTIFICATION_ID);
ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT FK_AUTH_IDENT
FOREIGN KEY (IDENTIFICATION_ID)
REFERENCES IDENTIFICATION (IDENTIFICATION_ID);
ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT CHK_ACCESS_LEVEL
CHECK (ACCESS_LEVEL IN ('user', 'support', 'admin'));

/* Додаткові перевірки змісту */
ALTER TABLE USER_T ADD CONSTRAINT CHK_USER_PREFS_LEN
CHECK (LENGTH(PREFERENCES) <= 200);
ALTER TABLE USER_T ADD CONSTRAINT CHK_USER_NOTIF_LEN
CHECK (LENGTH(NOTIFICATION_SETTINGS) <= 100);
ALTER TABLE ORDER_T ADD CONSTRAINT CHK_ORDER_DISHES_LEN
CHECK (LENGTH(DISHES) <= 500);
