name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-22.04
    steps:
      - name: Print Node Version
        run: node --version

  PrintDBMSVersions:
    runs-on: ubuntu-22.04
    needs: PrintLanguageVersions
    steps:
      - name: Download Oracle Instant Client
        run: |
          sudo apt-get update
          sudo apt-get install -y libaio1 wget unzip
          wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip -O instantclient.zip
          unzip instantclient.zip -d $HOME/oracle
          echo "$HOME/oracle/instantclient_21_13" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$HOME/oracle/instantclient_21_13" >> $GITHUB_ENV

      - name: Print Oracle SQL
        run: |
          $HOME/oracle/instantclient_21_13/sqlplus -V
