name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-22.04
    steps:
      - name: Print Node Version
        run: node --version

  PrintDBMSVersions:
    runs-on: ubuntu-22.04
    needs: PrintLanguageVersions
    steps:
      - name: Add MongoDB 7.0 APT repo
        run: |
          sudo apt-get update
          wget -qO - https://pgp.mongodb.com/server-7.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-7.0.gpg
          echo "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
      - name: Install MongoDB
        run: sudo apt-get install -y mongodb-org
      - name: Print MongoDB Version
        run: mongod --version
